version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/code
    networks:
      - backend
    container_name: fastapi
    depends_on: 
      - db
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb_data:
